# Generated by Django 6.0.1 on 2026-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_invitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contact",
            new_name="hr_contacts_workspa_eeb3d2_idx",
            old_name="hr_contacts_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="contact",
            new_name="hr_contacts_super_g_4e6256_idx",
            old_name="hr_contacts_super_g_idx",
        ),
        migrations.RenameIndex(
            model_name="contact",
            new_name="hr_contacts_user_id_e4111c_idx",
            old_name="hr_contacts_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="hr_invitati_token_7ef8fc_idx",
            old_name="hr_invitat_token_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="hr_invitati_email_74df66_idx",
            old_name="hr_invitat_email_idx",
        ),
        migrations.AlterField(
            model_name="contact",
            name="tariff_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
                verbose_name="Tariff rate",
            ),
        ),
    ]
