# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_ensure_personal_project_and_reassign"),
        ("finance", "0008_rename_finance_category_ws_type_idx_finance_cat_workspa_308805_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0003_rename_hr_contacts_workspa_idx_hr_contacts_workspa_eeb3d2_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to="core.workspacemember",
                        verbose_name="Head",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="hr.department",
                        verbose_name="Parent department",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_departments",
                        to="core.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "hr_departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_title", models.CharField(blank=True, max_length=128, verbose_name="Job title")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ONBOARDING", "Onboarding"),
                            ("ON_LEAVE", "On Leave"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("date_hired", models.DateField(blank=True, null=True, verbose_name="Date hired")),
                ("date_terminated", models.DateField(blank=True, null=True, verbose_name="Date terminated")),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACTOR", "Contractor"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                        verbose_name="Employment type",
                    ),
                ),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="FTE",
                        help_text="Full Time Equivalent",
                    ),
                ),
                (
                    "salary_mode",
                    models.CharField(
                        choices=[("FIXED", "Fixed (monthly)"), ("HOURLY", "Hourly")],
                        default="FIXED",
                        max_length=20,
                        verbose_name="Salary mode",
                    ),
                ),
                (
                    "salary_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Salary amount",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Currency")),
                ("settings", models.JSONField(blank=True, default=dict, verbose_name="Settings")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to="core.workspacemember",
                        verbose_name="Workspace member",
                    ),
                ),
                (
                    "payment_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_employee_profiles",
                        to="finance.wallet",
                        verbose_name="Payment wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee profile",
                "verbose_name_plural": "Employee profiles",
                "db_table": "hr_employee_profiles",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VACATION", "Vacation"),
                            ("SICK_LEAVE", "Sick leave"),
                            ("UNPAID", "Unpaid"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="core.workspacemember",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave request",
                "verbose_name_plural": "Leave requests",
                "db_table": "hr_leave_requests",
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField(verbose_name="Period start")),
                ("period_end", models.DateField(verbose_name="Period end")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total amount",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Currency")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PAID", "Paid")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Paid at")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_runs",
                        to="core.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll run",
                "verbose_name_plural": "Payroll runs",
                "db_table": "hr_payroll_runs",
            },
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Gross amount",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Net amount",
                    ),
                ),
                (
                    "days_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Days worked",
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Hours worked",
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(blank=True, default=dict, verbose_name="Calculation details"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is paid")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_items",
                        to="hr.employeeprofile",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hr.payrollrun",
                        verbose_name="Payroll run",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_item",
                        to="finance.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll item",
                "verbose_name_plural": "Payroll items",
                "db_table": "hr_payroll_items",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["workspace"], name="hr_departme_workspa_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(fields=["member"], name="hr_employee_member__idx"),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(fields=["status"], name="hr_employee_status__idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["member"], name="hr_leavereq_member__idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="hr_leavereq_status__idx"),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["workspace"], name="hr_payrollr_workspa_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["status"], name="hr_payrollr_status__idx"),
        ),
        migrations.AddIndex(
            model_name="payrollitem",
            index=models.Index(fields=["payroll_run"], name="hr_payrolli_payroll_idx"),
        ),
        migrations.AddConstraint(
            model_name="payrollitem",
            constraint=models.UniqueConstraint(
                fields=("payroll_run", "employee"),
                name="hr_payrollitem_payroll_run_employee_uniq",
            ),
        ),
    ]
