# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_hr_employee_payroll"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("OFFER", "Offer"),
                            ("CONTRACT", "Contract"),
                            ("NDA", "NDA"),
                            ("PASSPORT", "Passport"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Document type",
                    ),
                ),
                ("file", models.FileField(upload_to="hr/employee_docs/%Y/%m/", verbose_name="File")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Display name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employeeprofile",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee document",
                "verbose_name_plural": "Employee documents",
                "db_table": "hr_employee_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(fields=["employee"], name="hr_employee_employe_idx"),
        ),
    ]
