# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_employeedocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["super_group", "last_name", "first_name"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.AlterModelOptions(
            name="employeedocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Документ сотрудника",
                "verbose_name_plural": "Документы сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "verbose_name": "Профиль сотрудника",
                "verbose_name_plural": "Профили сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "verbose_name": "Приглашение",
                "verbose_name_plural": "Приглашения",
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "verbose_name": "Заявка на отпуск",
                "verbose_name_plural": "Заявки на отпуск",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollitem",
            options={
                "verbose_name": "Строка расчёта зарплаты",
                "verbose_name_plural": "Строки расчёта зарплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollrun",
            options={
                "verbose_name": "Расчёт зарплаты",
                "verbose_name_plural": "Расчёты зарплаты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="payrollitem",
            name="hr_payrollitem_payroll_run_employee_uniq",
        ),
        migrations.RenameIndex(
            model_name="department",
            new_name="hr_departme_workspa_54b78c_idx",
            old_name="hr_departme_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="employeedocument",
            new_name="hr_employee_employe_7122f7_idx",
            old_name="hr_employee_employe_idx",
        ),
        migrations.RenameIndex(
            model_name="employeeprofile",
            new_name="hr_employee_member__e3ec7e_idx",
            old_name="hr_employee_member__idx",
        ),
        migrations.RenameIndex(
            model_name="employeeprofile",
            new_name="hr_employee_status_c7379b_idx",
            old_name="hr_employee_status__idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="hr_leave_re_member__d2210b_idx",
            old_name="hr_leavereq_member__idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="hr_leave_re_status_af4e04_idx",
            old_name="hr_leavereq_status__idx",
        ),
        migrations.RenameIndex(
            model_name="payrollitem",
            new_name="hr_payroll__payroll_47bf97_idx",
            old_name="hr_payrolli_payroll_idx",
        ),
        migrations.RenameIndex(
            model_name="payrollrun",
            new_name="hr_payroll__workspa_5b0a77_idx",
            old_name="hr_payrollr_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="payrollrun",
            new_name="hr_payroll__status_a5a9e2_idx",
            old_name="hr_payrollr_status__idx",
        ),
        migrations.AlterUniqueTogether(
            name="payrollitem",
            unique_together={("payroll_run", "employee")},
        ),
    ]
