# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_schedule_entry_datetime_required"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scheduleentry",
            name="schedule_en_date_70f757_idx",
        ),
        migrations.RenameIndex(
            model_name="resource",
            new_name="resources_workspa_145405_idx",
            old_name="resources_workspace_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduleentry",
            new_name="schedule_en_start_t_01c5cf_idx",
            old_name="schedule_entries_time_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduleentry",
            new_name="schedule_en_resourc_72c2a0_idx",
            old_name="schedule_entries_resource_idx",
        ),
    ]
