# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_remove_scheduleentry_schedule_en_date_70f757_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"verbose_name": "Ресурс", "verbose_name_plural": "Ресурсы"},
        ),
        migrations.AlterModelOptions(
            name="scheduleentry",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Запись расписания",
                "verbose_name_plural": "Записи расписания",
            },
        ),
    ]
