# Generated by Django 5.0.1 on 2026-01-27 21:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress (%)')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Hours')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Actual Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='todo.workitem', verbose_name='Dependencies')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.project', verbose_name='Project')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='documents.tag', verbose_name='Tags')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Watchers')),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'db_table': 'work_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='projects_workspa_658984_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='work_items_status_7d4a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['due_date'], name='work_items_due_dat_a56e31_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['project'], name='work_items_project_707743_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['created_at'], name='work_items_created_6a1494_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['priority', 'status'], name='work_items_priorit_d8b6aa_idx'),
        ),
    ]
