# Generated by Django 6.0.1 on 2026-01-31 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_workitem_finance_project_budget"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workitem",
            new_name="work_items_source__d69f8b_idx",
            old_name="work_items_source__a1b2c3_idx",
        ),
    ]
