# Generated by Django - WorkItem.sort_order for Kanban column ordering

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_work_items_source__a1b2c3_idx_work_items_source__d69f8b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Порядок внутри колонки на общей доске', verbose_name='Sort Order'),
        ),
    ]
