# Generated by Django 6.0.1 on 2026-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0004_alter_stage_options_and_more"),
        ("todo", "0010_add_hourly_rate_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitem",
            name="kanban_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Текущая колонка канбана",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workitems_direct",
                to="kanban.column",
                verbose_name="Kanban Column",
            ),
        ),
    ]
