# Generated by Django 6.0.1 on 2026-02-03 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0016_task_dependency"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="checklistitem",
            new_name="checklist_i_workite_0d7efb_idx",
            old_name="checklist_i_workite_idx",
        ),
        migrations.RenameIndex(
            model_name="taskdependency",
            new_name="task_depend_predece_7cc934_idx",
            old_name="task_depen_predece_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="work_items_stage_i_f032a9_idx",
            old_name="work_items_stage_id_1a2b3c_idx",
        ),
    ]
