# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0020_backfill_workitem_stage_from_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitem",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Пункт чек-листа",
                "verbose_name_plural": "Пункты чек-листа",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="taskdependency",
            options={
                "verbose_name": "Зависимость задач",
                "verbose_name_plural": "Зависимости задач",
            },
        ),
        migrations.AlterModelOptions(
            name="workitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
