# Generated by Django 6.0.1 on 2026-01-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_updated", "Task Updated"),
                    ("task_commented", "Task Commented"),
                    ("deadline_approaching", "Deadline Approaching"),
                    ("deadline_passed", "Deadline Passed"),
                    ("project_updated", "Project Updated"),
                    ("budget_alert", "Budget Alert"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
