# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Журнал аудита",
                "verbose_name_plural": "Журналы аудита",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
