# Generated by Django 6.0.1 on 2026-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_category_tag_post_category_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier (auto from title if empty)",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
