# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Категория блога",
                "verbose_name_plural": "Категории блога",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Тег блога",
                "verbose_name_plural": "Теги блога",
            },
        ),
    ]
