# Generated by Django 5.0.1 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posted_to_telegram",
            field=models.BooleanField(default=False, verbose_name="Posted to Telegram"),
        ),
        migrations.AddField(
            model_name="post",
            name="posted_to_vk",
            field=models.BooleanField(default=False, verbose_name="Posted to VK"),
        ),
    ]
