# Generated by Django 6.0.1 on 2026-01-31 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_role_company_workspace_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=6, verbose_name="Verification Code"),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Change"),
                            ("login", "Login"),
                        ],
                        default="registration",
                        max_length=20,
                        verbose_name="Code Type",
                    ),
                ),
                (
                    "telegram_contact",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username или номер телефона",
                        max_length=255,
                        null=True,
                        verbose_name="Telegram Contact",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Password Hash",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Code",
                "verbose_name_plural": "Verification Codes",
                "db_table": "verification_codes",
                "indexes": [
                    models.Index(
                        fields=["code", "telegram_contact"],
                        name="verificatio_code_a24687_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="verificatio_expires_bef114_idx"
                    ),
                ],
            },
        ),
    ]
