# Generated by Django 6.0.1 on 2026-02-03 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_projectmember_contact"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_project_e547cf_idx",
            old_name="project_mem_project_6a8c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_user_id_f59cbb_idx",
            old_name="project_mem_user_id_9f3d4b_idx",
        ),
    ]
