# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_socialidentity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Участник проекта",
                "verbose_name_plural": "Участники проекта",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="verificationcode",
            options={
                "verbose_name": "Код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
            },
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Рабочее пространство",
                "verbose_name_plural": "Рабочие пространства",
            },
        ),
        migrations.AlterModelOptions(
            name="workspacemember",
            options={
                "verbose_name": "Участник рабочего пространства",
                "verbose_name_plural": "Участники рабочего пространства",
            },
        ),
        migrations.RenameIndex(
            model_name="socialidentity",
            new_name="social_iden_provide_7f7dba_idx",
            old_name="social_ident_provider_2262bc_idx",
        ),
        migrations.RenameIndex(
            model_name="socialidentity",
            new_name="social_iden_user_id_a2e7bb_idx",
            old_name="social_ident_user_id_18fbe7_idx",
        ),
    ]
