# Generated by Django 6.0.1 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_aiagent_monthly_cost_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiagent",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "HR"),
                    ("finance", "Finance"),
                    ("assistant", "Assistant"),
                    ("manager", "Manager"),
                    ("analyst", "Analyst"),
                ],
                default="assistant",
                max_length=32,
                verbose_name="Role (slug)",
            ),
        ),
    ]
