# Generated by Django 5.0.1 on 2026-01-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('all_day', models.BooleanField(default=False, verbose_name='All Day')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, verbose_name='Recurrence Rule')),
                ('color', models.CharField(default='#3788d8', max_length=7, verbose_name='Color')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 'calendar_events',
                'ordering': ['start_date'],
            },
        ),
    ]
