# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Событие календаря",
                "verbose_name_plural": "События календаря",
            },
        ),
    ]
