# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_project_bebff2_idx",
            old_name="invoices_project_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_status_07776b_idx",
            old_name="invoices_status_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_date_is_42e6ca_idx",
            old_name="invoices_date_issue_idx",
        ),
    ]
