# Generated by Django 6.0.1 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_subscription_plan_obj_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                help_text="Дублирует plan_obj для совместимости",
                max_length=20,
                verbose_name="Plan (legacy)",
            ),
        ),
    ]
