# Generated by Django 5.0.1 on 2026-03-04 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_payment_transactions_and_webhooks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billingaccount",
            new_name="billing_acc_status_2d1635_idx",
            old_name="billing_acco_status_18f881_idx",
        ),
        migrations.RenameIndex(
            model_name="billingaccount",
            new_name="billing_acc_owner_i_126aee_idx",
            old_name="billing_acco_owner_i_911dc8_idx",
        ),
        migrations.RenameIndex(
            model_name="billingsubscription",
            new_name="billing_sub_account_4729f1_idx",
            old_name="billing_bil_account_a2cab9_idx",
        ),
        migrations.RenameIndex(
            model_name="billingsubscription",
            new_name="billing_sub_current_46f785_idx",
            old_name="billing_bil_current_d43726_idx",
        ),
        migrations.RenameIndex(
            model_name="entitlementoverride",
            new_name="billing_ent_account_ffd860_idx",
            old_name="billing_ent_account_21100d_idx",
        ),
        migrations.RenameIndex(
            model_name="entitlementoverride",
            new_name="billing_ent_expires_87885c_idx",
            old_name="billing_ent_expires_871972_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="billing_pay_account_ac9f44_idx",
            old_name="billing_paym_account_7cbfe2_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="billing_pay_provide_680804_idx",
            old_name="billing_paym_provider_ba9846_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentwebhookevent",
            new_name="billing_pay_provide_08897b_idx",
            old_name="billing_paym_provider_17016a_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentwebhookevent",
            new_name="billing_pay_event_t_e7cbf2_idx",
            old_name="billing_paym_event_t_b3b798_idx",
        ),
        migrations.RenameIndex(
            model_name="planversion",
            new_name="billing_pla_code_5c4b60_idx",
            old_name="billing_plan_code_8dd33e_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionitem",
            new_name="billing_sub_subscri_7e78a6_idx",
            old_name="billing_sub_subscription_87f476_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionitem",
            new_name="billing_sub_code_37826a_idx",
            old_name="billing_sub_code_24579f_idx",
        ),
        migrations.RenameIndex(
            model_name="usagemeter",
            new_name="billing_usa_is_acti_1d3de7_idx",
            old_name="billing_usag_is_acti_5f7c7e_idx",
        ),
        migrations.RenameIndex(
            model_name="usagerecord",
            new_name="billing_usa_account_995952_idx",
            old_name="billing_usa_account_39437b_idx",
        ),
        migrations.RenameIndex(
            model_name="usagerecord",
            new_name="billing_usa_source_8e9443_idx",
            old_name="billing_usa_source_154f12_idx",
        ),
    ]
