# Generated by Django 6.0.1 on 2026-01-31 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_project_299495_idx",
            old_name="transaction_project_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_workite_2ca594_idx",
            old_name="transaction_workitem_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_created_5c02ac_idx",
            old_name="transaction_created_idx",
        ),
    ]
