# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_add_related_timelog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_project_299495_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_workite_2ca594_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transactions_created_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_project_db9105_idx",
            old_name="transactions_project_type_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_related_08df64_idx",
            old_name="transactions_workitem_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_related_eb4f06_idx",
            old_name="transactions_timelog_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
