# Generated by Django 6.0.1 on 2026-02-11 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_ensure_personal_project_and_reassign"),
        ("finance", "0007_finance_v2"),
        (
            "hr",
            "0003_rename_hr_contacts_workspa_idx_hr_contacts_workspa_eeb3d2_idx_and_more",
        ),
        ("timetracking", "0003_timelog_is_paid_paid_at"),
        ("todo", "0020_backfill_workitem_stage_from_column"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="finance_cat_workspa_308805_idx",
            old_name="finance_category_ws_type_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_source__22027b_idx",
            old_name="finance_tx_source_wallet_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_destina_7ba0bc_idx",
            old_name="finance_tx_dest_wallet_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_transfe_4f723e_idx",
            old_name="finance_tx_transfer_group_idx",
        ),
        migrations.RenameIndex(
            model_name="wallet",
            new_name="finance_wal_owner_i_096cac_idx",
            old_name="finance_wallet_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="wallet",
            new_name="finance_wal_workspa_1da044_idx",
            old_name="finance_wallet_workspace_idx",
        ),
        migrations.RenameIndex(
            model_name="wallet",
            new_name="finance_wal_is_acti_15a83a_idx",
            old_name="finance_wallet_active_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = системная категория.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_categories",
                to="core.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Всегда положительное число", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payroll_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Устаревшее поле для payroll, оставлено для совместимости.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_transactions",
                to="hr.contact",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="todo.project",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="related_timelog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_transactions",
                to="timetracking.timelog",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="related_workitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_transactions",
                to="todo.workitem",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("spend", "Spend"),
                    ("transfer", "Transfer"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец (личный кошелек).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace (бизнес-кошелек).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="core.workspace",
            ),
        ),
    ]
