# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0008_rename_finance_category_ws_type_idx_finance_cat_workspa_308805_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankconnection",
            options={
                "verbose_name": "Банковское подключение",
                "verbose_name_plural": "Банковские подключения",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория (финансы)",
                "verbose_name_plural": "Категории (финансы)",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Кошелёк", "verbose_name_plural": "Кошельки"},
        ),
    ]
