# Generated by Django 5.0.1 on 2026-01-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Stopped At')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('billable', models.BooleanField(default=True, verbose_name='Billable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='todo.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Time Log',
                'verbose_name_plural': 'Time Logs',
                'db_table': 'time_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workitem', 'user'], name='time_logs_workite_520310_idx'), models.Index(fields=['started_at'], name='time_logs_started_699c79_idx')],
            },
        ),
    ]
