# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0003_timelog_is_paid_paid_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelog",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Тайм-лог",
                "verbose_name_plural": "Тайм-логи",
            },
        ),
    ]
