# Generated by Django 6.0.1 on 2026-02-04 14:17

import apps.saas.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="limits",
            field=models.JSONField(
                default=apps.saas.models.default_limits,
                help_text="max_system_contacts, max_ai_agents, features",
                verbose_name="Limits",
            ),
        ),
    ]
