# Generated by Django 5.0.1 on 2026-03-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_saasplatformsettings_landing_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplatformsettings',
            name='default_landing_category',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
