# Generated by Django 5.0.1 on 2026-03-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_default_landing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplatformsettings',
            name='landing_company_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saasplatformsettings',
            name='landing_lead_requests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saasplatformsettings',
            name='landing_pending_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saasplatformsettings',
            name='landing_private_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
