# Generated by Django 5.0.1 on 2026-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_landing_reviews_and_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplatformsettings',
            name='landing_default_version',
            field=models.CharField(blank=True, default='v2', max_length=16),
        ),
    ]
