# Generated by Django 5.0.1 on 2026-01-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='todo.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'db_table': 'boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('column_type', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed')], default='todo', max_length=50, verbose_name='Column Type')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('wip_limit', models.IntegerField(blank=True, null=True, verbose_name='WIP Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.board', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'db_table': 'columns',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('days_in_column', models.IntegerField(default=0, verbose_name='Days in Column')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('related_workitem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='todo.workitem', verbose_name='Related Work Item')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.column', verbose_name='Column')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['project'], name='boards_project_2b0204_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['board', 'position'], name='columns_board_i_edff8e_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['column', 'position'], name='cards_column__a87af9_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['due_date'], name='cards_due_dat_243c97_idx'),
        ),
    ]
