# Generated by Django 6.0.1 on 2026-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0003_stage_system_type_progress_health"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
            },
        ),
        migrations.RemoveIndex(
            model_name="column",
            name="columns_board_i_edff8e_idx",
        ),
        migrations.AlterField(
            model_name="column",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="kanban.stage",
                verbose_name="Stage",
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["stage", "position"], name="columns_stage_i_6e559e_idx"
            ),
        ),
    ]
