# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0007_rename_plan_column_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["position"],
                "verbose_name": "Колонка канбана",
                "verbose_name_plural": "Колонки канбана",
            },
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Этап (канбан)",
                "verbose_name_plural": "Этапы (канбан)",
            },
        ),
    ]
