# Generated by Django 5.0.1 on 2026-01-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.workitem', verbose_name='Work Item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.comment', verbose_name='Parent Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.workitem', verbose_name='Work Item'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.workspace', verbose_name='Workspace'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['workitem'], name='attachments_workite_0bd6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by'], name='attachments_uploade_77499a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['workitem', 'created_at'], name='comments_workite_384afe_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='comments_author__25752a_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['workspace'], name='tags_workspa_384c1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'workspace')},
        ),
    ]
