# Generated by Django 5.0.1 on 2026-01-28 00:51

import apps.documents.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0002_initial'),
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'verbose_name_plural': 'Wiki Pages',
                'db_table': 'wiki_pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited At'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is Edited'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=apps.documents.utils.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='workitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.workitem', verbose_name='Work Item (Legacy)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='workitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.workitem', verbose_name='Work Item (Legacy)'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='attachments_content_7c0e26_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['project'], name='attachments_project_454a91_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_type'], name='attachments_file_ty_5fd764_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='comments_content_85d9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_parent__9f8798_idx'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='wiki_pages', to='documents.attachment', verbose_name='Attachments'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.wikipage', verbose_name='Parent Page'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='todo.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wiki_pages', to='documents.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Watchers'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['project', 'slug'], name='wiki_pages_project_4a5902_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['project', 'parent', 'order'], name='wiki_pages_project_4ea7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['author'], name='wiki_pages_author__722935_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['is_published'], name='wiki_pages_is_publ_4f77d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('slug', 'project')},
        ),
    ]
