# Generated by Django 6.0.1 on 2026-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_wikipage_workspace_workitem_optional_project"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="wikipage",
            new_name="wiki_pages_workspa_b9e2ad_idx",
            old_name="wiki_pages_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="wikipage",
            new_name="wiki_pages_workite_d4d5f3_idx",
            old_name="wiki_pages_workite_idx",
        ),
    ]
