# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_wikipage_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterModelOptions(
            name="wikipage",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Страница вики",
                "verbose_name_plural": "Страницы вики",
            },
        ),
    ]
