# Generated by Django 6.0.1 on 2026-01-31 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="company",
            new_name="companies_inn_1e26b0_idx",
            old_name="companies_inn_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companies_type_e9b519_idx",
            old_name="companies_type_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companies_name_c7a1b3_idx",
            old_name="companies_name_idx",
        ),
    ]
