# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_add_customer_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_workspa_c918bb_idx",
            old_name="customers_workspace_status_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_name_25d5e3_idx",
            old_name="customers_name_idx",
        ),
    ]
