# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0004_rename_customers_workspace_status_idx_customers_workspa_c918bb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["name"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
