# Generated by Django 5.0.1 on 2026-01-27 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gantt.gantttask', verbose_name='Parent Task')),
                ('related_workitem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gantt_task', to='todo.workitem', verbose_name='Related Work Item')),
            ],
            options={
                'verbose_name': 'Gantt Task',
                'verbose_name_plural': 'Gantt Tasks',
                'db_table': 'gantt_tasks',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GanttDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2, verbose_name='Dependency Type')),
                ('lag', models.IntegerField(default=0, verbose_name='Lag (days)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='gantt.gantttask', verbose_name='Predecessor')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='gantt.gantttask', verbose_name='Successor')),
            ],
            options={
                'verbose_name': 'Gantt Dependency',
                'verbose_name_plural': 'Gantt Dependencies',
                'db_table': 'gantt_dependencies',
            },
        ),
        migrations.AddIndex(
            model_name='gantttask',
            index=models.Index(fields=['start_date', 'end_date'], name='gantt_tasks_start_d_402065_idx'),
        ),
        migrations.AddIndex(
            model_name='gantttask',
            index=models.Index(fields=['related_workitem'], name='gantt_tasks_related_cfc469_idx'),
        ),
        migrations.AddIndex(
            model_name='gantttask',
            index=models.Index(fields=['parent'], name='gantt_tasks_parent__b1c071_idx'),
        ),
        migrations.AddIndex(
            model_name='ganttdependency',
            index=models.Index(fields=['predecessor', 'successor'], name='gantt_depen_predece_b51f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ganttdependency',
            unique_together={('predecessor', 'successor')},
        ),
    ]
