# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gantt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ganttdependency",
            options={
                "verbose_name": "Зависимость Ганта",
                "verbose_name_plural": "Зависимости Ганта",
            },
        ),
        migrations.AlterModelOptions(
            name="gantttask",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Задача Ганта",
                "verbose_name_plural": "Задачи Ганта",
            },
        ),
    ]
