# Generated by Django 6.0.1 on 2026-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0003_advertisement_video_blog_content_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="content_type",
            field=models.CharField(
                choices=[("image", "Image"), ("html", "HTML"), ("video", "Video")],
                default="image",
                max_length=16,
                verbose_name="Content type",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="slot",
            field=models.CharField(
                choices=[
                    ("sidebar", "Sidebar"),
                    ("footer_col_1", "Footer column 1"),
                    ("footer_col_2", "Footer column 2"),
                    ("footer_col_3", "Footer column 3"),
                    ("blog_content", "Blog (inside article)"),
                ],
                max_length=32,
                verbose_name="Slot",
            ),
        ),
    ]
