# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0004_alter_advertisement_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "ordering": ["slot", "sort_order", "id"],
                "verbose_name": "Рекламный блок",
                "verbose_name_plural": "Рекламные блоки",
            },
        ),
    ]
