# Generated by Django 6.0.1 on 2026-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mindmaps", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mindmap",
            new_name="mindmaps_mi_workspa_d01e9e_idx",
            old_name="mindmaps_workspace_idx",
        ),
        migrations.RenameIndex(
            model_name="mindmap",
            new_name="mindmaps_mi_project_0f716c_idx",
            old_name="mindmaps_project_idx",
        ),
        migrations.RenameIndex(
            model_name="mindmap",
            new_name="mindmaps_mi_related_fa498a_idx",
            old_name="mindmaps_workitem_idx",
        ),
        migrations.RenameIndex(
            model_name="mindmap",
            new_name="mindmaps_mi_owner_i_df92ee_idx",
            old_name="mindmaps_owner_pers_idx",
        ),
    ]
