# Generated by Django 6.0.1 on 2026-03-02 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mindmaps",
            "0002_rename_mindmaps_workspace_idx_mindmaps_mi_workspa_d01e9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mindmap",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Карта мыслей",
                "verbose_name_plural": "Карты мыслей",
            },
        ),
    ]
